packages:
  - packages/client
  - packages/stoat.js
  - packages/solid-livekit-components
  - packages/solid-dnd-directive
  - packages/js-lingui-solid/packages/*
nodeLinker: isolated
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
